version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db_bookings
    env_file:
      - .env  
    volumes:
      - ./src:/src  
    working_dir: /src 
    command: ["python", "Bookings.py"]
